"""Structured multi-period financial statement extraction."""

from __future__ import annotations

import re
from collections.abc import Iterable

from ...models import Evidence, FinancialStatement, StatementRow
from ..document_processing_agent.processor import PageText


_NUMBER_PATTERN = re.compile(r"\(?[-+]?\d[\d,]*(?:\.\d+)?\)?")

_STATEMENT_MARKERS = {
    "income_statement": (
        "consolidated statements of operations",
        "consolidated statement of operations",
        "income statement",
        "statement of profit or loss",
    ),
    "balance_sheet": (
        "consolidated balance sheets",
        "consolidated balance sheet",
        "statement of financial position",
    ),
    "cash_flow_statement": (
        "consolidated statements of cash flows",
        "consolidated statement of cash flows",
        "cash flow statement",
    ),
}

_ROW_ALIASES: dict[str, dict[str, tuple[str, ...]]] = {
    "income_statement": {
        "revenue": ("total net sales", "total revenue", "revenue"),
        "cost_of_revenue": ("total cost of sales", "cost of revenue"),
        "gross_profit": ("gross margin", "gross profit"),
        "operating_expenses": ("total operating expenses",),
        "operating_income": ("operating income", "operating profit"),
        "pretax_income": ("income before provision for income taxes", "profit before tax"),
        "income_tax_expense": ("provision for income taxes", "income tax expense"),
        "net_income": ("net income", "profit for the year"),
    },
    "balance_sheet": {
        "cash_and_equivalents": ("cash and cash equivalents",),
        "current_assets": ("total current assets",),
        "total_assets": ("total assets",),
        "current_liabilities": ("total current liabilities",),
        "total_liabilities": ("total liabilities",),
        "total_equity": (
            "total shareholders' equity",
            "total shareholders’ equity",
            "total stockholders' equity",
            "total equity",
        ),
        "commercial_paper": ("commercial paper",),
        "term_debt": ("term debt",),
    },
    "cash_flow_statement": {
        "operating_cash_flow": (
            "cash generated by operating activities",
            "net cash provided by operating activities",
        ),
        "capital_expenditure": (
            "payments for acquisition of property, plant and equipment",
            "purchases of property, plant and equipment",
        ),
        "investing_cash_flow": ("cash used in investing activities",),
        "financing_cash_flow": ("cash used in financing activities",),
        "ending_cash": ("cash, cash equivalents and restricted cash, ending balances",),
    },
}


def _normalize(value: str) -> str:
    return " ".join(value.casefold().replace("’", "'").split()).rstrip(".:")


def _parse_number(value: str) -> float:
    negative = value.startswith("(") and value.endswith(")")
    number = float(value.strip("()").replace(",", ""))
    return -number if negative else number


def _periods(lines: list[str]) -> tuple[str, ...]:
    years: list[str] = []
    for line in lines[:24]:
        for year in re.findall(r"\b(?:19|20)\d{2}\b", line):
            if year not in years:
                years.append(year)
    return tuple(years)


def _statement_type(text: str) -> str | None:
    normalized = _normalize(text)
    for name, markers in _STATEMENT_MARKERS.items():
        if any(marker in normalized for marker in markers):
            return name
    return None


def _unit_metadata(text: str) -> tuple[str, int]:
    lowered = text.lower()
    if "in billions" in lowered:
        return "billions", 1_000_000_000
    if "in millions" in lowered or "in milions" in lowered:
        return "millions", 1_000_000
    if "in thousands" in lowered:
        return "thousands", 1_000
    return "units", 1


def _currency(text: str) -> str:
    if "£" in text:
        return "GBP"
    if "€" in text:
        return "EUR"
    if "$" in text:
        return "USD"
    return "unknown"


def _values_after(lines: list[str], start: int, count: int) -> list[float]:
    values: list[float] = []
    for line in lines[start : start + 14]:
        for match in _NUMBER_PATTERN.findall(line):
            values.append(_parse_number(match))
            if len(values) == count:
                return values
    return values


def _matching_indexes(lines: list[str], aliases: tuple[str, ...]) -> list[int]:
    normalized_aliases = {_normalize(alias) for alias in aliases}
    return [index for index, line in enumerate(lines) if _normalize(line) in normalized_aliases]


def _row_values(
    lines: list[str], aliases: tuple[str, ...], periods: tuple[str, ...]
) -> tuple[dict[str, float], str] | None:
    matches = _matching_indexes(lines, aliases)
    if not matches:
        return None
    aggregate = [0.0] * len(periods)
    evidence_parts: list[str] = []
    valid_occurrences = 0
    for index in matches:
        values = _values_after(lines, index, len(periods))
        if len(values) != len(periods):
            continue
        valid_occurrences += 1
        aggregate = [left + right for left, right in zip(aggregate, values)]
        evidence_parts.append(" ".join(lines[index : index + len(periods) + 3]))
    if not valid_occurrences:
        return None
    return dict(zip(periods, aggregate)), " | ".join(evidence_parts)[:500]


def _extract_eps(lines: list[str], periods: tuple[str, ...], page: int) -> dict[str, StatementRow]:
    rows: dict[str, StatementRow] = {}
    section = next(
        (index for index, line in enumerate(lines) if _normalize(line) == "earnings per share"),
        None,
    )
    if section is None:
        return rows
    for name in ("basic", "diluted"):
        index = next(
            (
                position
                for position in range(section + 1, min(section + 18, len(lines)))
                if _normalize(lines[position]) == name
            ),
            None,
        )
        if index is None:
            continue
        values = _values_after(lines, index, len(periods))
        if len(values) == len(periods):
            row_name = f"{name}_eps"
            rows[row_name] = StatementRow(
                row_name,
                dict(zip(periods, values)),
                Evidence(page, " ".join(lines[index : index + len(periods) + 4])[:500]),
            )
    return rows


def extract_statements(pages: Iterable[PageText]) -> dict[str, FinancialStatement]:
    statements: dict[str, FinancialStatement] = {}
    for page in pages:
        statement_name = _statement_type(page.text)
        if not statement_name:
            continue
        lines = [" ".join(line.split()) for line in page.text.splitlines() if line.strip()]
        periods = _periods(lines)
        if not periods:
            continue
        rows: dict[str, StatementRow] = {}
        for row_name, aliases in _ROW_ALIASES[statement_name].items():
            extracted = _row_values(lines, aliases, periods)
            if extracted:
                values, evidence_text = extracted
                rows[row_name] = StatementRow(
                    row_name, values, Evidence(page.number, evidence_text)
                )
        if statement_name == "income_statement":
            rows.update(_extract_eps(lines, periods, page.number))
        if statement_name == "balance_sheet" and "term_debt" in rows:
            debt_components = [rows["term_debt"]]
            if "commercial_paper" in rows:
                debt_components.append(rows["commercial_paper"])
            total_debt_values = {
                period: sum(row.values.get(period, 0) for row in debt_components)
                for period in periods
            }
            rows["total_debt"] = StatementRow(
                "total_debt",
                total_debt_values,
                Evidence(page.number, "Derived from commercial paper and term debt."),
            )
        unit, scale = _unit_metadata(page.text)
        candidate = FinancialStatement(
            name=statement_name,
            periods=periods,
            rows=rows,
            currency=_currency(page.text),
            unit=unit,
            unit_scale=scale,
            page=page.number,
        )
        existing = statements.get(statement_name)
        if existing is None or len(candidate.rows) > len(existing.rows):
            statements[statement_name] = candidate
    return statements
