"""Structured multi-period financial statement extraction."""

from __future__ import annotations

import re
from collections.abc import Iterable

from ...models import Evidence, FinancialStatement, StatementRow
from ..agent_01_document_processing.processor import PageText


_NUMBER_PATTERN = re.compile(r"\(?[-+]?\d[\d,]*(?:\.\d+)?\)?")

_STATEMENT_MARKERS = {
    "income_statement": (
        "consolidated statements of operations",
        "consolidated statement of operations",
        "income statement",
        "consolidated statements of income",
        "consolidated statement of income",
        "statement of profit or loss",
    ),
    "balance_sheet": (
        "consolidated balance sheets",
        "consolidated balance sheet",
        "statement of financial position",
    ),
    "cash_flow_statement": (
        "consolidated statements of cash flows",
        "consolidated statement of cash flows",
        "cash flow statement",
    ),
}

_ROW_ALIASES: dict[str, dict[str, tuple[str, ...]]] = {
    "income_statement": {
        "revenue": ("total net sales", "net sales", "total revenue", "revenue"),
        "cost_of_revenue": ("total cost of sales", "cost of sales", "cost of revenue"),
        "gross_profit": ("gross margin", "gross profit"),
        "operating_expenses": ("total operating expenses",),
        "operating_income": ("operating income", "operating profit"),
        "pretax_income": ("income before provision for income taxes", "profit before tax"),
        "income_tax_expense": ("provision for income taxes", "income tax expense"),
        "net_income": ("net income", "profit for the year"),
    },
    "balance_sheet": {
        "cash_and_equivalents": ("cash and cash equivalents",),
        "current_assets": ("total current assets",),
        "total_assets": ("total assets",),
        "current_liabilities": ("total current liabilities",),
        "total_liabilities": ("total liabilities",),
        "total_equity": (
            "total shareholders' equity",
            "total shareholders’ equity",
            "total stockholders' equity",
            "total equity",
        ),
        "total_liabilities_and_equity": (
            "total liabilities and stockholders' equity",
            "total liabilities and shareholders' equity",
            "total liabilities and equity",
        ),
        "commercial_paper": ("commercial paper",),
        "term_debt": (
            "term debt",
            "long-term debt",
            "short-term debt",
            "debt payable within one-year",
        ),
    },
    "cash_flow_statement": {
        "beginning_cash": (
            "cash, cash equivalents and restricted cash, beginning balances",
            "cash and cash equivalents at beginning of year",
            "cash, cash equivalents, and restricted cash, beginning of period",
        ),
        "operating_cash_flow": (
            "cash generated by operating activities",
            "net cash provided by operating activities",
            "net cash provided by operations",
            "net cash provided by (used in) operating activities",
        ),
        "capital_expenditure": (
            "payments for acquisition of property, plant and equipment",
            "purchases of property, plant and equipment",
            "purchases of property and equipment",
            "capital expenditures",
        ),
        "investing_cash_flow": (
            "cash used in investing activities",
            "net cash provided by (used in) investing activities",
            "net cash used in investing activities",
        ),
        "financing_cash_flow": (
            "cash used in financing activities",
            "net cash provided by (used in) financing activities",
            "net cash used in financing activities",
        ),
        "ending_cash": (
            "cash, cash equivalents and restricted cash, ending balances",
            "cash and cash equivalents at end of year",
            "cash, cash equivalents, and restricted cash, end of period",
        ),
        "net_change_in_cash": (
            "net increase (decrease) in cash, cash equivalents, and restricted cash",
            "increase (decrease) in cash, cash equivalents and restricted cash",
            "decrease in cash, cash equivalents and restricted cash",
            "net increase (decrease) in cash and cash equivalents",
        ),
        "foreign_exchange_effect": (
            "foreign currency effect on cash, cash equivalents, and restricted cash",
            "effect of exchange rate changes on cash and cash equivalents",
        ),
    },
}

_DASHES = {"—", "–", "-"}


def _normalize(value: str) -> str:
    return " ".join(value.casefold().replace("’", "'").split()).rstrip(".:")


def _slug(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "_", _normalize(value)).strip("_")
    return slug[:100] or "unnamed_row"


def _parse_number(value: str) -> float:
    negative = value.startswith("(") and value.endswith(")")
    number = float(value.strip("()").replace(",", ""))
    return -number if negative else number


def _periods(lines: list[str]) -> tuple[str, ...]:
    years: list[str] = []
    for line in lines[:24]:
        for year in re.findall(r"\b(?:19|20)\d{2}\b", line):
            if year not in years:
                years.append(year)
    return tuple(years)


def _statement_type(text: str) -> str | None:
    normalized = _normalize(text)
    for name, markers in _STATEMENT_MARKERS.items():
        if any(marker in normalized for marker in markers):
            return name
    return None


def _unit_metadata(text: str) -> tuple[str, int]:
    lowered = text.lower()
    if "in billions" in lowered:
        return "billions", 1_000_000_000
    if "in millions" in lowered or "in milions" in lowered:
        return "millions", 1_000_000
    if "in thousands" in lowered:
        return "thousands", 1_000
    return "units", 1


def _currency(text: str) -> str:
    if "£" in text:
        return "GBP"
    if "€" in text:
        return "EUR"
    if "$" in text:
        return "USD"
    return "unknown"


def _values_after(lines: list[str], start: int, count: int) -> list[float]:
    values: list[float] = []
    for line in lines[start : start + 14]:
        for match in _NUMBER_PATTERN.findall(line):
            values.append(_parse_number(match))
            if len(values) == count:
                return values
    return values


def _matching_indexes(lines: list[str], aliases: tuple[str, ...]) -> list[int]:
    normalized_aliases = {_normalize(alias) for alias in aliases}
    return [index for index, line in enumerate(lines) if _normalize(line) in normalized_aliases]


def _canonical_name(
    statement_name: str, label: str, section: str | None = None
) -> str | None:
    normalized = _normalize(label)
    normalized_section = _normalize(section or "")
    for row_name, aliases in _ROW_ALIASES[statement_name].items():
        if normalized in {_normalize(alias) for alias in aliases}:
            return row_name
    if statement_name == "income_statement":
        if normalized_section == "earnings per share" and normalized in {"basic", "diluted"}:
            return f"{normalized}_eps"
        if normalized.startswith("net income attributable to"):
            return "net_income"
        if normalized.startswith("earnings per common share, basic"):
            return "basic_eps"
        if normalized.startswith("earnings per common share, diluted"):
            return "diluted_eps"
        if normalized == "basic earnings per share":
            return "basic_eps"
        if normalized == "diluted earnings per share":
            return "diluted_eps"
    return None


def _is_section(line: str) -> bool:
    stripped = line.strip()
    return bool(
        stripped.endswith(":")
        or _normalize(stripped)
        in {
            "assets",
            "liabilities and stockholders' equity",
            "liabilities and shareholders' equity",
            "liabilities and shareholders’ equity",
            "current assets",
            "current liabilities",
            "stockholders' equity",
            "shareholders' equity",
            "shareholders’ equity",
            "operating activities",
            "investing activities",
            "financing activities",
            "supplemental cash flow information",
            "operating expenses",
        }
    )


def _line_value_tokens(line: str) -> list[tuple[int, int, float]]:
    tokens: list[tuple[int, int, float]] = []
    for match in _NUMBER_PATTERN.finditer(line):
        tokens.append((match.start(), match.end(), _parse_number(match.group())))
    if not tokens and line.strip() in _DASHES:
        tokens.append((0, len(line), 0.0))
    return tokens


def _unique_key(rows: dict[str, StatementRow], preferred: str, section: str | None) -> str:
    if preferred not in rows:
        return preferred
    section_key = _slug(section or "")
    if section_key and f"{section_key}_{preferred}" not in rows:
        return f"{section_key}_{preferred}"
    counter = 2
    while f"{preferred}_{counter}" in rows:
        counter += 1
    return f"{preferred}_{counter}"


def _extract_complete_rows(
    statement_name: str,
    lines: list[str],
    periods: tuple[str, ...],
    page: int,
) -> tuple[dict[str, StatementRow], tuple[str, ...]]:
    """Retain every label/value row in PDF order, not only known KPI rows."""
    rows: dict[str, StatementRow] = {}
    sections: list[str] = []
    section: str | None = None
    label_parts: list[str] = []
    pending_values: list[float] = []
    evidence_parts: list[str] = []
    period_count = len(periods)
    last_period_index = max(
        (index for index, line in enumerate(lines[:30]) if _normalize(line) in periods),
        default=0,
    )

    def finalize() -> None:
        nonlocal label_parts, pending_values, evidence_parts
        label = " ".join(label_parts).strip(" .")
        if label and len(pending_values) == period_count:
            canonical = _canonical_name(statement_name, label, section)
            key = _unique_key(rows, canonical or _slug(label), section)
            rows[key] = StatementRow(
                name=key,
                values=dict(zip(periods, pending_values)),
                evidence=Evidence(page, " ".join(evidence_parts)[:500]),
                label=label,
                section=section,
            )
        label_parts = []
        pending_values = []
        evidence_parts = []

    for line in lines[last_period_index + 1 :]:
        compact = " ".join(line.split())
        if not compact or compact == "$":
            continue
        normalized = _normalize(compact)
        if normalized.startswith("see accompanying notes"):
            finalize()
            break
        tokens = _line_value_tokens(compact)
        if _is_section(compact) and not tokens:
            finalize()
            section = compact.rstrip(":")
            if section not in sections:
                sections.append(section)
            continue

        if tokens:
            trailing_text = compact[tokens[-1][1] :].strip(" ,.;:)]}")
            if trailing_text and any(character.isalpha() for character in trailing_text):
                if pending_values:
                    finalize()
                label_parts.append(compact)
                evidence_parts.append(compact)
                continue
            if len(tokens) >= period_count:
                finalize()
                selected = tokens[-period_count:]
                prefix = compact[: selected[0][0]].strip(" $.")
                if prefix:
                    label_parts.append(prefix)
                pending_values = [token[2] for token in selected]
                evidence_parts.append(compact)
                finalize()
            else:
                prefix = compact[: tokens[0][0]].strip(" $.")
                if prefix:
                    label_parts.append(prefix)
                pending_values.extend(token[2] for token in tokens)
                evidence_parts.append(compact)
                if len(pending_values) == period_count:
                    finalize()
                elif len(pending_values) > period_count:
                    pending_values = pending_values[-period_count:]
                    finalize()
            continue

        if pending_values:
            finalize()
        label_parts.append(compact)
        evidence_parts.append(compact)

    finalize()
    return rows, tuple(sections)


def _row_values(
    lines: list[str], aliases: tuple[str, ...], periods: tuple[str, ...]
) -> tuple[dict[str, float], str] | None:
    matches = _matching_indexes(lines, aliases)
    if not matches:
        return None
    aggregate = [0.0] * len(periods)
    evidence_parts: list[str] = []
    valid_occurrences = 0
    for index in matches:
        values = _values_after(lines, index, len(periods))
        if len(values) != len(periods):
            continue
        valid_occurrences += 1
        aggregate = [left + right for left, right in zip(aggregate, values)]
        evidence_parts.append(" ".join(lines[index : index + len(periods) + 3]))
    if not valid_occurrences:
        return None
    return dict(zip(periods, aggregate)), " | ".join(evidence_parts)[:500]


def _extract_eps(lines: list[str], periods: tuple[str, ...], page: int) -> dict[str, StatementRow]:
    rows: dict[str, StatementRow] = {}
    section = next(
        (index for index, line in enumerate(lines) if _normalize(line) == "earnings per share"),
        None,
    )
    if section is None:
        return rows
    for name in ("basic", "diluted"):
        index = next(
            (
                position
                for position in range(section + 1, min(section + 18, len(lines)))
                if _normalize(lines[position]) == name
            ),
            None,
        )
        if index is None:
            continue
        values = _values_after(lines, index, len(periods))
        if len(values) == len(periods):
            row_name = f"{name}_eps"
            rows[row_name] = StatementRow(
                row_name,
                dict(zip(periods, values)),
                Evidence(page, " ".join(lines[index : index + len(periods) + 4])[:500]),
                label=name.title(),
                section="Earnings per share",
            )
    return rows


def extract_statements(pages: Iterable[PageText]) -> dict[str, FinancialStatement]:
    statements: dict[str, FinancialStatement] = {}
    for page in pages:
        statement_name = _statement_type(page.text)
        if not statement_name:
            continue
        lines = [" ".join(line.split()) for line in page.text.splitlines() if line.strip()]
        periods = _periods(lines)
        if not periods:
            continue
        rows, sections = _extract_complete_rows(statement_name, lines, periods, page.number)
        # Fall back to canonical targeted extraction if a difficult OCR layout misses a row.
        for row_name, aliases in _ROW_ALIASES[statement_name].items():
            if row_name in rows:
                continue
            extracted = _row_values(lines, aliases, periods)
            if extracted:
                values, evidence_text = extracted
                rows[row_name] = StatementRow(
                    row_name,
                    values,
                    Evidence(page.number, evidence_text),
                    label=aliases[0],
                )
        if statement_name == "income_statement":
            for row_name, row in _extract_eps(lines, periods, page.number).items():
                rows.setdefault(row_name, row)
        if statement_name == "balance_sheet" and any(
            _canonical_name(statement_name, row.label) == "term_debt"
            for row in rows.values()
        ):
            debt_components = [
                row
                for row in rows.values()
                if _canonical_name(statement_name, row.label)
                in {"term_debt", "commercial_paper"}
            ]
            total_debt_values = {
                period: sum(row.values.get(period, 0) for row in debt_components)
                for period in periods
            }
            rows["total_debt"] = StatementRow(
                "total_debt",
                total_debt_values,
                Evidence(page.number, "Derived from commercial paper and term debt."),
                label="Total debt",
            )
        unit, scale = _unit_metadata(page.text)
        candidate = FinancialStatement(
            name=statement_name,
            periods=periods,
            rows=rows,
            currency=_currency(page.text),
            unit=unit,
            unit_scale=scale,
            page=page.number,
            sections=sections,
        )
        existing = statements.get(statement_name)
        if existing is None or len(candidate.rows) > len(existing.rows):
            statements[statement_name] = candidate
    return statements
