from fris.agents.agent_04_data_quality import validate_financials
from fris.agents.agent_01_document_processing import PageText
from fris.agents.agent_02_metrics_extraction import (
    extract_statements,
    select_primary_statement_pages,
)
from fris.agents.agent_03_financial_calculation_engine import calculate_period_ratios


def _apple_statement_pages() -> list[PageText]:
    return [
        PageText(
            32,
            "CONSOLIDATED STATEMENTS OF OPERATIONS\n(In millions)\n"
            "2022\n2021\n2020\n"
            "Total net sales\n394,328\n365,817\n274,515\n"
            "Total cost of sales\n223,546\n212,981\n169,559\n"
            "Gross margin\n170,782\n152,836\n104,956\n"
            "Operating income\n119,437\n108,949\n66,288\n"
            "Net income\n99,803\n94,680\n57,411\n"
            "Earnings per share:\nBasic\n6.15\n5.67\n3.31\n"
            "Diluted\n6.11\n5.61\n3.28",
        ),
        PageText(
            34,
            "CONSOLIDATED BALANCE SHEETS\n(In millions)\n2022\n2021\n"
            "Total current assets\n135,405\n134,836\n"
            "Total assets\n352,755\n351,002\n"
            "Commercial paper\n9,982\n6,000\n"
            "Term debt\n11,128\n9,613\n"
            "Term debt\n98,959\n109,106\n"
            "Total current liabilities\n153,982\n125,481\n"
            "Total liabilities\n302,083\n287,912\n"
            "Total shareholders’ equity\n50,672\n63,090",
        ),
        PageText(
            36,
            "CONSOLIDATED STATEMENTS OF CASH FLOWS\n(In millions)\n"
            "2022\n2021\n2020\n"
            "Cash generated by operating activities\n122,151\n104,038\n80,674\n"
            "Payments for acquisition of property, plant and equipment\n"
            "(10,708)\n(11,085)\n(7,309)",
        ),
    ]


def test_extracts_periods_units_and_structured_rows() -> None:
    selected_pages = select_primary_statement_pages(_apple_statement_pages())
    statements = extract_statements(selected_pages)

    assert [page.number for page in selected_pages] == [32, 34, 36]

    income = statements["income_statement"]
    assert income.periods == ("2022", "2021", "2020")
    assert income.unit == "millions"
    assert income.unit_scale == 1_000_000
    assert income.rows["revenue"].values["2021"] == 365_817

    balance = statements["balance_sheet"]
    assert balance.rows["total_debt"].values["2022"] == 120_069


def test_calculates_expanded_period_metrics() -> None:
    statements = extract_statements(_apple_statement_pages())
    ratios = calculate_period_ratios(statements)

    assert ratios["2022"]["working_capital"].value == -18_577
    assert ratios["2022"]["asset_turnover"].value == 1.12
    assert ratios["2022"]["return_on_assets"].value == 28.36
    assert ratios["2022"]["return_on_equity"].value == 175.46
    assert ratios["2022"]["debt_to_equity"].value == 2.37
    assert ratios["2022"]["debt_ratio"].value == 0.34
    assert ratios["2022"]["free_cash_flow"].value == 111_443
    assert ratios["2022"]["basic_eps"].value == 6.15


def test_financial_equations_validate_for_all_available_periods() -> None:
    statements = extract_statements(_apple_statement_pages())
    ratios = calculate_period_ratios(statements)
    validations = validate_financials(statements, ratios)

    assert len(validations) == 7
    assert all(validation.passed for validation in validations)
